disabled_rules:
  - todo
  - opening_brace
  - cyclomatic_complexity
  - function_parameter_count
  - force_try
included:
  - Clipy
excluded:
  - Pods
line_length: 200
identifier_name:
  excluded:
    - i
