included:
  - Clipy/Sources
  - ClipyTests
excluded:
  - Pods
opt_in_rules:
  - empty_count
  - explicit_init
  - closure_spacing
  - overridden_super_call
  - redundant_nil_coalescing
  - private_outlet
  - nimble_operator
  - operator_usage_whitespace
  - closure_end_indentation
  - first_where
  - fatal_error_message
  - vertical_parameter_alignment_on_call
  - let_var_whitespace
  - unneeded_parentheses_in_closure_argument
  - extension_access_modifier
  - pattern_matching_keywords
  - literal_expression_end_indentation
  - joined_default_parameter
  - contains_over_first_not_nil
  - override_in_extension
  - private_action
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - single_test_class
  - yoda_condition
disabled_rules:
  - todo
  - cyclomatic_complexity
  - force_try
identifier_name:
  excluded:
    - i
line_length: 300
type_body_length:
  - 300
  - 400
file_length:
  warning: 500
  error: 1000
function_body_length:
  warning: 100
  error: 200
