os: osx
osx_image:
  - xcode10.2
  - xcode11
language: objective-c
xcode_workspace: Clipy.xcworkspace
xcode_scheme: Clipy
xcode_destination: platform=macOS
before_install:
  - gem install xcpretty bundler cocoapods
  - bundle install
  - pod install --repo-update