os: osx
osx_image:
  - xcode11
language: objective-c
xcode_workspace: Clipy.xcworkspace
xcode_scheme: Clipy
xcode_destination: platform=macOS
before_install:
  - gem install xcpretty bundler 'cocoapods:1.7.5'
install:
  - bundle install --jobs=3 --retry=3 --deployment
  - pod install --repo-update --deployment
script:
  - fastlane mac release
deploy:
  provider: releases
  api_key: "${GITHUB_OAUTH_TOKEN}"
  file: "Clipy.app"
  skip_cleanup: true
  on:
    tags: true
