language: objective-c
osx_image: xcode7.2
os: osx
xcode_workspace: Clipy.xcworkspace
xcode_scheme:
  - Clipy
script: xctool -workspace Clipy.xcworkspace -scheme "Clipy" build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
before_install:
  - gem install cocoapods -v '0.39.0'
  - pod install
# enable container-based infrastructure
sudo: false
cache: bundler
