name: Actionlint

on:
  pull_request:
    paths:
      - ".github/workflows/**"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  actionlint:
    name: Lint workflows
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write # required for reviewdog to report actionlint results via the Checks API
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - uses: reviewdog/action-actionlint@dbe5299849118fd6f099ba563d263d770955a64a # v1.73.2
