name: CI

on: [push, pull_request]

env:
  DEVELOPER_DIR: /Applications/Xcode_26.2.app/Contents/Developer

jobs:
  test:
    runs-on: macos-26
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Setup ruby
      uses: ruby/setup-ruby@c4e5b1316158f92e3d49443a9d58b31d25ac0f8f # v1.306.0
      with:
        ruby-version: '3.4'
        bundler-cache: true
        
    - name: Cache CocoaPods
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-

    - name: Pod install
      run: bundle exec pod install

    - name: Run fastlane
      run: bundle exec fastlane test
    