name: Zizmor

on:
  push:
    branches:
      - develop
      - master
  pull_request: {}

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  zizmor:
    name: Security audit
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write # required to upload zizmor's SARIF results to code scanning
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - uses: zizmorcore/zizmor-action@6fc4b006235f201fdab3722e17240ab420d580e5 # v0.6.1
